Managing Vehicles in the administrator menu
40346200Aidan/SET09402CW pull request #49
Opened 2024-07-16 23:45 UTC by ShaunL12345

STILL WIP 
updates the database initiation process to drop tables and creates data for the vehicle table
also adds a new screen for managing vehicles

2024-07-17 07:24 UTC, 40081168LJ requested changes
Please see comments to be updated.

2024-07-17 07:24 UTC, 40081168LJ commented on HaulageApplication/Haulage/DatabaseSetup.cs
>                  CREATE TABLE IF NOT EXISTS item (
Naming conventions should be followed throughout, used lowercase for table name, used starting acpital followed by camel case. Please update to "Item".

2024-07-17 07:24 UTC, 40081168LJ commented on HaulageApplication/Haulage/DatabaseSetup.cs
>                  CREATE TABLE IF NOT EXISTS user (
Naming conventions should be followed throughout, used lowercase for table name, used starting acpital followed by camel case. Please update to "User".

2024-07-19 20:28 UTC, 40346200Aidan approved these changes, later dismissed
Looks good, Approved

2024-07-26 21:21 UTC, 40081168LJ submitted a review, later dismissed
LJ - Update sections and see if test coverage can at least get to 50% +.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/AdminPages/AddVehiclePage.xaml.cs
LJ - Update the clearing out function of SaveVehicle_Clicked, maybe display message on clear/fail/success, etc.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/AdminPages/AddVehiclePage.xaml.cs
LJ - Also write to console for debugging.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/AdminPages/ManageVehiclesPage.xaml.cs
LJ - Update the clearing out function of RemoveVehicle_Clicked, maybe display message on clear/fail/success, etc.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/AppShell.xaml
LJ - Remove this, as not needed.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/BaseClasses/Accounting/Vehicle.cs
LJ - Update code for StatusTypes to be releavant.

2024-07-26 21:21 UTC, 40081168LJ commented on HaulageApplication/Haulage/DatabaseExecutionServices/VehicleExecutionService.cs
LJ - Clear spacing in SQL. Spacing between functions, clear to 1 line.

2024-07-26 22:39 UTC, ShaunL12345 commented on HaulageApplication/Haulage/AdminPages/AddVehiclePage.xaml.cs
have updated this

2024-07-26 22:46 UTC, ShaunL12345 commented on HaulageApplication/Haulage/AdminPages/ManageVehiclesPage.xaml.cs
done

2024-07-26 22:47 UTC, ShaunL12345 commented on HaulageApplication/Haulage/AppShell.xaml
done

2024-07-26 22:52 UTC, ShaunL12345 commented on HaulageApplication/Haulage/BaseClasses/Accounting/Vehicle.cs
have updated this

2024-07-26 23:15 UTC, ShaunL12345 commented on HaulageApplication/Haulage/DatabaseExecutionServices/VehicleExecutionService.cs
have done this

2024-07-27 20:33 UTC, SBoer33 approved these changes

2024-07-27 20:34 UTC, merged