confirm pickup and delivery of items
40346200Aidan/SET09402CW pull request #78
Opened 2024-08-21 14:22 UTC by ShaunL12345

2024-08-26 17:38 UTC, 40346200Aidan requested changes

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/AdminPages/AddVehiclePage.xaml.cs
fine with this addition of error handling and removing of redundant whitespace

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/BaseClasses/TripHandler/Item.cs
Empty inspectItem method should be removed or complete

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/BaseClasses/TripHandler/PickupRequest.cs
Fine with this change of an additional status within the enum

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DatabaseExecutionServices/ItemExecutionService.cs
Fine with this change, well-formatted code. Methods also do not contain too much functionality and each have one purpose

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DatabaseSetup.cs
Fine with this change with changing the datatype of columns and additional test data

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DriverPage.xaml
xaml formatting is done well fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DriverPage.xaml.cs
fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DriverPages/ConfirmPickupDeliveryPage.xaml
maybe worth having the first label within the items collection view start with grid row like the rest for readability but small change. Formatting of xaml is fine

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/DriverPages/ConfirmPickupDeliveryPage.xaml.cs
Code well formatted, fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/Haulage.csproj
Fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/Haulage.csproj.user
Fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/Models/ItemModel.cs
Fine with this change, good use of adhering to naming conventions for classes, and methods

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/Haulage/ViewModels/ItemViewModel.cs
Fine with this change

2024-08-26 17:38 UTC, 40346200Aidan commented on HaulageApplication/HaulageTests/ItemTests.cs
Tests cover numerous aspects of the functionality of the feature. It may be worth implementing tests for buttons on pages but fine with this change

2024-08-27 17:07 UTC, 40346200Aidan approved these changes

2024-08-27 17:07 UTC, merged

2024-08-27 23:23 UTC, ShaunL12345 commented on HaulageApplication/Haulage/BaseClasses/TripHandler/Item.cs
this is being used as a blueprint for future development